import style from './page.module.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={style.main}>
      {children}
      <div className={style.foote}r>
      <p>copzright: eder da silva amorim e erick da silva amorim</p>
      </div>
      </body>
    </html>
  )
}
